export default vinhos = [
  {
    nome: "Sangue de Boi",
    tipo: "Tinto",
    safra: "2018",
    pais: "Brasil",
    regiao: "Serra Gaúcha",
    produtor: "Vinícola Aurora",
    uva: "Cabernet Sauvignon",
    imagem: "",
  },
  {
    nome: "Château Margaux",
    tipo: "Tinto",
    safra: "2015",
    pais: "França",
    regiao: "Bordeaux",
    produtor: "Château Margaux",
    uva: "Cabernet Sauvignon",
    imagem: "",
  },
  {
    nome: "Ridge Monte Bello",
    tipo: "Tinto",
    safra: "2017",
    pais: "Estados Unidos",
    regiao: "Califórnia",
    produtor: "Ridge Vineyards",
    uva: "Cabernet Sauvignon",
    imagem: "",
  },
  {
    nome: "Bodega Catena Zapata Adrianna Vineyard Malbec",
    tipo: "Tinto",
    safra: "2016",
    pais: "Argentina",
    regiao: "Mendoza",
    produtor: "Bodega Catena Zapata",
    uva: "Malbec",
    imagem: "",
  },
  {
    nome: "Quinta do Noval Nacional Vintage Port",
    tipo: "Vinho do Porto",
    safra: "2017",
    pais: "Portugal",
    regiao: "Douro",
    produtor: "Quinta do Noval",
    uva: "Blend",
    imagem: "",
  },
];
